---
title: "US COVID-19 Recoveries"
author: "David J Jackson"
date: "4/28/2020 3:25pm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
            width=9, fig.height=6)
library(tidyverse)
library(RSQLite)
library(scales)
library(plotly)
library(patchwork)
library(ggeasy)
theme_set(theme_light())
```
```{r}
db <- dbConnect(SQLite(), dbname="../COVIDDB/CORVID.sqlite3")
```
```{r}
US <- dbGetQuery(db, "SELECT * FROM JHUDATA 
                 WHERE country ='US'")
US$date <- as.Date(US$date)

US <- US%>% mutate(daily_deaths = deaths - lag(deaths))
US <- US%>% mutate(daily_cases = confirmed - lag(confirmed))
US <- US%>% mutate(daily_recovery = recovered - lag(recovered))
```

#### US Recoveries  by Date (Daily and Accumliated)

```{r}
plot1 <- US %>% ggplot() + geom_line(aes(x=date,y=recovered),col="blue",lwd=1) + 
  labs(title="US Accumliated Recoveries to Date",
       capton="(Source: https://coronavirus.jhu.edu/map.html")  
   
  
ggplotly(plot1)
```
```{r}
plot2 <- US %>% ggplot() + geom_line(aes(x=date,y=daily_recovery),col="blue",lwd=1) + 
  labs(title="US Daily Recoveries by Date",
       caption="(https://coronavirus.jhu.edu/map.html)")
ggplotly(plot2)
```

#### Comparing Daily Cases to Recoveries

```{r}
US %>% ggplot() + geom_line(aes(x=date,y=daily_recovery,col="Recoveries"),lwd=1) + 
  labs(title="US Daily Cases and Recoveries by Date",
       caption="(Source: https://coronavirus.jhu.edu/map.html)",
       y="Daily Cases and Recoveries",subtitle="Apr. 25, 2020") + 
  geom_line(aes(x=date,y=daily_cases,col="Cases"),lwd=1) +
  easy_remove_x_axis()

```
```{r}
US %>% ggplot() + geom_line(aes(x=date,y=daily_recovery,col="Recoveries"),lwd=1) + 
  labs(title="US Daily Cases and Recoveries by Date",
       caption="(Source: https://coronavirus.jhu.edu/map.html)",
       y="Log of Daily Cases and Recoveries",subtitle="Apr. 25,2020") + 
  geom_line(aes(x=date,y=daily_cases,col="Cases"),lwd=1) +
  scale_y_log10()
```

```{r}

US %>% ggplot() + 
  geom_line(aes(x=date,y=daily_recovery,col="Recoveries"),lwd=1) + 
    labs(title="US Daily Cases and Recoveries by Date" ,
       y="Daily Cases and Recoveries",subtitle="Apr. 25, 2020") + 
    geom_line(aes(x=date,y=daily_cases,col="Cases"),lwd=1) +
  easy_remove_x_axis()

```
```{r}
US %>% ggplot() + geom_line(aes(x=date,y=daily_recovery,col="Recoveries"),lwd=1) + 
  labs(title="US Daily Cases and Recoveries by Date",
       caption="(Source: https://coronavirus.jhu.edu/map.html)",
       y="Log of Daily Cases and Recoveries") + 
  geom_line(aes(x=date,y=daily_cases,col="Cases"),lwd=1) +
  scale_y_log10()
```

#### Flatting the Curve

```{r}
US %>% ggplot() + geom_line(aes(x=date,y=daily_deaths),col="blue",lwd=1) + 
      labs(title="US  Deaths by Date",
       y="Log10 Scale",
       caption="(https://coronavirus.jhu.edu/map.html)") +
  scale_y_log10()

```
```{r}
US %>% ggplot() + geom_line(aes(x=date,y=daily_cases),col="blue",lwd=1) + 
      labs(title="US Cases by Date",
       y="Log10 Scale",
       caption="(https://coronavirus.jhu.edu/map.html)") +
  scale_y_log10()
  
```
```{r}
US %>% ggplot() + geom_line(aes(x=date,y=daily_recovery),col="blue",lwd=1) + 
      labs(title="US Recoveries by Date",
       y="Log10 Scale",
       caption="(https://coronavirus.jhu.edu/map.html)") +
  scale_y_log10()
  
```

## European CDC Daily Cases and Deaths

```{r}
ECDC <- dbGetQuery(db, "SELECT * FROM ECDC 
                 WHERE Countries ='USA'")
ECDC$Reported <- as.Date(ECDC$Reported)
```
```{r}
ECDC %>% ggplot() + geom_line(aes(x=Reported,y=Cases),col="Red",lwd=1) + 
      labs(title="US  Cases by Date",
       y="Log10 of Cases",
       caption="(Source: European CDc)") +
  scale_y_log10()

```
```{r}
ECDC %>% ggplot() + geom_line(aes(x=Reported,y=Deaths),col="Red",lwd=1) + 
      labs(title="US  Deaths by Date",
       y="Log10 Scale",
       caption="(Source: European CDC)") +
  scale_y_log10() 
```



