---
title: 'GGPLOT2: Us in a Nutshell'
author: "David Jackson"
date: "10/10/2020"
output: 
  html_document: 
    fig_width: 10
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE)
library(RSQLite)
library(ggplot2)
library(scales)
library(plotly)
library(esquisse)
theme_set(theme_linedraw())
```

```{r,echo=FALSE}
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
df <- dbGetQuery(db,"select * from JHUDATA")
df$date <- as.Date(df$date)
df <- df[order(df$date,decreasing = TRUE),]
df <- subset(df,country =="US")
str(df)

```

### GGPLOt2 Plots of Cumulative Cases and Deaths
#### Source: New York Times

```{r,echo=FALSE}
cumm_cases <-ggplot(df) +geom_line(aes(x=date,y=confirmed),lwd=3,col="red") + 
    scale_x_date(date_breaks = "1 month") +
  scale_y_continuous(labels = comma) +
   theme(axis.text.x=element_text(angle =- 45, vjust = 0.5)) +
  labs(title="US Cumulative Total Cases",
       x="Date date",y="Cumulative Cases") 
```
```{r}
cumm_deaths <-ggplot(df) +geom_line(aes(x=date,y=deaths),lwd=3,col="blue") + 
    scale_x_date(date_breaks = "1 month") +
  scale_y_continuous(labels = comma) +
   theme(axis.text.x=element_text(angle =- 45, vjust = 0.5)) +
  labs(title="US Cumulative Total Deaths",x="Date date",y="Cumulative Deaths")
ggplotly(cumm_cases)
ggplotly(cumm_deaths)
```

## GGPLOt2 Plots of Daily Deaths and Cases
#### Source: European CDPC

```{r, echo=FALSE}
df1 <- read.csv("../DATA/USCOVID.csv")
df1$date <- lubridate::ymd(df1$date)
df1 <- df1[order(df1$date,decreasing = TRUE),]
df1death <- df1 %>% filter(date>="2020-02-29") 

```

#### Average US Covid-19 Deaths/day

```{r}
mean(df1death$Deaths)
```

### NPR/Washington Uni 300,000 by Dec. 1,2020 

```{r}
(300000 - sum(df1death$Deaths))/59
sum(df1death$Deaths) + (59 *mean(df1death$Deaths))

```

### Washington Uni and Yahoo/USA Today: 
#### 410,000 Jan. 1 2021

```{r}
(410000 - sum(df1death$Deaths)) / 90 # Jan 1, 2021
sum(df1death$Deaths) + (90 *mean(df1death$Deaths))
```
#### Average Deaths/Day for Jan. 31, 2021
#### 410,000 

```{r}
(410000 - sum(df1death$Deaths))/ 120 # Jan 31, 2020
sum(df1death$Deaths) + (120 *mean(df1death$Deaths))
```



```{r,echo=FALSE}

p1 <-ggplot(df1) +geom_line(aes(x=date,y=Cases,col="red"),lwd=2,col="red") + 
    scale_x_date(date_breaks = "1 month") +
  scale_y_continuous(labels = comma) +
   theme(axis.text.x=element_text(angle =- 45, vjust = 0.5)) +
  labs(title="US Daily Total Cases(2020-03-01 - 2020-09-08)",x="Date date",y="Daily Cases")
ggplotly(p1)
```
```{r,echo=FALSE}
ggplot(df1death) +geom_line(aes(x=date,y=Deaths),lwd=2,col="blue") + 
    scale_x_date(date_breaks = "1 month") +
  scale_y_continuous(labels = comma) +
   theme(axis.text.x=element_text(angle =- 45, vjust = 0.5)) +
  labs(title="US Daily Total Deaths(2020-03-01 - 2020-09-08)",
       subtitle="Daily Avg (Black:961); Dec. 1 (Blue:1550);  Jan. 1 (Green:2238); Jan. 31 (Red:1679)"
       ,x="Date date",y="Daily Deaths") +
  geom_hline(yintercept=961,lwd=2,col="black") +
  geom_hline(yintercept=1550,lwd=1,col="blue") +
  geom_hline(yintercept=2238,lwd=1,col="green") +
   geom_hline(yintercept=1679,lwd=1,col="red")
```



#### Histograms of Daily Cases and Deaths

```{r, echo=FALSE}
ggplot(df1) + geom_histogram(aes(x=Deaths))   +
  labs(title="Histogram of Daily Deaths")

ggplot(df1) + geom_histogram(aes(x=Cases))   +
  labs(title="Histogram of Daily Cases")
  
```
```{r}
ggplot(df1) + geom_bar(aes(x=Deaths,fill=..count..),stat="bin")
ggplot(df1) + geom_bar(aes(x=Cases,fill=..count..),stat="bin")
```

