---
title: "US Mortality Rate by State"
author: "David Jackson"
date: "10/1/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(RSQLite)
theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))
```
```{r}
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
df <- dbGetQuery(db,"select * from STATESDAILY")
df <- subset(df,date =="2020-09-30"  )
#
df <- df[order(df$date,decreasing = TRUE),]
```

### Mortality Rate by State

```{r}
df$Rate <- df$TotalDeaths/df$PreviousTotalCases
df <- df[order(df$Rate,decreasing = TRUE),]
```

```{r}
ggplot(df) + geom_col(aes(x=reorder(state,Rate),y=Rate)) +
  scale_y_continuous(labels = scales::percent) + coord_flip() +
  labs(title="US Mortality Rate by State as for Sept 30, 2020",x="Mortality Rate (%)",y="US State",
       caption = "(Source New York Times")
  
```

