---
title: "United States COVID-19 Vaccine Rollout"
author: "David Jackson"
date: "03/14/2021 12:10 PM/EST"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
library(ggplot2)
library(scales)
library(RSQLite)
library(plotly)
library(dplyr)
library(tidyr)
library(forecast)
# theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))
theme_set(theme_light())
```

## Sweden COVID-19 Rollout
### Our World In Data: http://ourworldindata.org

```{r}
rm(list=ls())

db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVID-19-DB/OURWORLD.sqlite3")
SWE <- dbGetQuery(db,"select * from OWID where location ='United States'")
SWE$date <- as.Date(SWE$date)
```
```{r}
VAC <- SWE %>% filter(date >="2020-12-25") %>% 
  select(date,people_vaccinated, people_fully_vaccinated,
         new_vaccinations,total_vaccinations,population)
```

### Individual Plot for Each Type of Vaccination

#### total_vaccinations
*Total number of COVID-19 vaccination doses administered.

```{r}

p1 <- VAC %>% filter(date>="2021-01-27") %>% ggplot() + geom_line(aes(x=date,y=total_vaccinations)) +
  scale_y_continuous(labels=comma) +
  labs(title="total_vaccinations")
ggplotly(p1)
```

#### people_vaccinated
* Total number of people who received at least one vaccine dose.

```{r}
p2 <- VAC %>% filter(date>="2021-01-27") %>% ggplot() + geom_line(aes(x=date,y=people_vaccinated,col="People Vacc.")) +
  geom_line(aes(x=date,y=people_fully_vaccinated, col="People Full Vac.")) +
  scale_y_log10(labels=comma) + 
  
  labs(title="Total Number people who have Received One Dose")
ggplotly(p2)
```


#### Percentage of People Vaccinated and Full Vaccinated

```{r}

VAC$PeoplePercent <- VAC$people_vaccinated/VAC$population
p3 <-VAC %>% filter(date >="2021-01-02") %>%
  ggplot(aes(x=date,y=PeoplePercent)) +
    geom_line() + scale_y_continuous(labels= percent) +
  labs(title="Percentage of People Receiving At Least Shot",
       y="Percent of Population")
ggplotly(p3)
```

```{r}

VAC$PeoplFullVac <- VAC$people_fully_vaccinated/VAC$population
```
```{r}
p4 <- VAC %>% filter(date >="2021-01-10") %>%
  ggplot(aes(x=date,y=PeoplFullVac)) +
    geom_line() + scale_y_continuous(labels= percent) +
  labs(title="Percentage of People Fully Vaccinated",
       y="Percent of Population")
ggplotly(p4)
```


